name: dino_run
description: A 2D infinite side scroller.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flame: 1.7.2
  flame_audio: 1.4.1
  hive: 2.2.3
  path_provider: 2.0.14
  provider: 6.0.5
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5

dev_dependencies:
  hive_generator: 2.0.0
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/audio/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
